version: 2.1

jobs:
  test:
    parameters:
      file:
        type: string
    docker:
      - image: cimg/base:current
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Install xq
          command: curl -sSL https://bit.ly/install-xq | sudo bash
      - run:
          name: validate << parameters.file >>
          command: xq << parameters.file >> || true
      - run:
          name: cat file with nonprintable characters shown
          command: cat -v << parameters.file >>
      - store_test_results:
          path: << parameters.file >>
      - run:
          name: notify on fail
          command: echo notify
          when: fail

workflows:
  main:
    jobs:
      - test:
          file: 'xml/customer.xml'
